### ISSUE TITLE
Success page

### ISSUE THREAD

**Issue by porras** [rubymonsters/rgbapp#10]
It now looks like this:

![screen shot 2017-03-06 at 20 32 55](https://cloud.githubusercontent.com/assets/3830/23626159/281380ac-02ac-11e7-8c75-bfeb4d5f0b3b.png)

It should be a bit more cheerful!

**Comment by ferbsx** [comment]
The confirmation page as of now:
# Rails Girls Berlin Beginners Workshop <date, eg: 25.3.2017>
Thank you for filling out the form!
If you see this message: Your application has been received. You will NOT receive a confirmation e-mail that we received your application. 

For queries regarding the application, please contact: contact@railsgirlsberlin.de. 

\<Submit another response>

![screen shot 2017-03-14 at 11 08 30 am](https://cloud.githubusercontent.com/assets/11502220/23895648/c7ada8fe-08a6-11e7-91e9-4a3fdadaa9cb.png)
