### ISSUE TITLE
minor change in wording on the new application form

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#115]
Hi there! So we have a new workshop planned and I was setting up the workshop application form and I had to fill this: 
![screen shot 2018-10-02 at 4 28 50 pm](https://user-images.githubusercontent.com/11502220/46359784-de63a600-c661-11e8-8493-0a9945a263bf.png)

and I thought this was the deadline by which the accepted attendees have to confirm their attendance, and not the date which I would be sending out the confirmation mails (like it is written on the final form which applicants see: )
![screen shot 2018-10-02 at 4 29 06 pm](https://user-images.githubusercontent.com/11502220/46359787-defc3c80-c661-11e8-8ecf-5ef72af6f977.png)

So I wanted to ask if you could change the wording on the "new event application" page to maybe  "Confirmation mails sent by:" instead of "Attendance to be confirmed by:".

Thank you 🌺

**Comment by ferbsx** [comment]
And what is actually the deadline the accepted attendees will get to confirm their attendance? 5 days after the confirmation mail is sent out?

**Comment by juopmu** [comment]
Yes. Applicants will have 5 days to confirm after they have received the e-mail telling them that they have been selected.
