### ISSUE TITLE
Bug in {{ Confirmation_deadline }}

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#116]
I was writing the application e-mail and I looked into the how-to part and thought of using the {{ confirmation_deadline }} variable instead of writing "October 14th" but it turned that into "31.12.2999" instead :/

![screen shot 2018-10-02 at 4 23 05 pm](https://user-images.githubusercontent.com/11502220/46360504-83cb4980-c663-11e8-9fe4-aea41a4ec4f7.png)

**Comment by juopmu** [comment]
At the moment, all variables are filled with fake data for the preview. The e-mails will contain the correct data, though.

**Comment by juopmu** [comment]
Since this may be confusing, we will improve it my using the real event data. We will still use fake data for the applicant.
