### ISSUE TITLE
send a "reminder to confirm attendance" email

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#186]
I would love if we can send an email to all the accepted people that have not yet confirmed their attendance on the confirmation deadline to remind them to confirm their attendance.

Default subject: 
"Confirm your attendance! Or your spot willl be given to someone else"

Default body: 
"Hi {{ applicant_name }}, 

You have apparently not confirmed your attendance yet! Do it right now before it's too late (**deadline is today**) by simply clicking this link: {{ confirmation_link }} . Please do write us a simple "sorry, can't make it." to contact@railsgirlsberlin.de, if you can not make it. This way we can make someone else happy by giving them your spot :) 

Cheers, 
Ferdous from code curious (formerly known as Rails Girls Berlin) Organisers team
"

**Comment by juopmu** [comment]
Could also include a cancel link. See my comment on #190.
