### ISSUE TITLE
{{confirmation_deadline}} shows the wrong date

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#187]
I'm not sure if I've understood this wrong or given in the wrong dates, so please help me out here.

I told the app the following details:
![Screen Shot 2019-06-03 at 12 21 37 PM](https://user-images.githubusercontent.com/11502220/58798383-5f60ac00-85fa-11e9-9f52-3b9c03c4a841.png)

So I'm going to choose the attendees and everything by 3rd of June midnight. I want the applicants to confirm their attendance by 5th of June midnight (so I'm giving them 2 full days to respond). 

But if I use the {{ confirmation_deadline }} tag, it should say 05.06.2019, but it says 08.06.2019 which is the workshop date. This is I think a bug. 🐛 

![Screen Shot 2019-06-03 at 12 15 12 PM](https://user-images.githubusercontent.com/11502220/58798033-74890b00-85f9-11e9-8206-2ca7ceaaf939.png)
![Screen Shot 2019-06-03 at 12 15 27 PM](https://user-images.githubusercontent.com/11502220/58798034-74890b00-85f9-11e9-9695-e7ec0b686eef.png)

Thank you all 😄

**Comment by juopmu** [comment]
@ferbsx Your're right. This does not work. We set the default to 5 days and the number you enter in the field - a text field - does not affect that at all. Is it OK to have you enter the number of days or would you prefer to choose the exact date in that field?

**Comment by ferbsx** [comment]
I see that you fixed it and chose to let the admin set the number of days. Thank you 🌺
