### ISSUE TITLE
Add column "Not confirmed in time" to the application form

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#189]
It would be really great if the app had a column "Not confirmed in time", where the applicants who were "selected" and hadn't confirmed by a certain date (which I could give in) would move to. 

This would make it easier for me, because when the deadline for the applicants, who have been accepted to confirm their attendance is passed, I would select applicants from the waiting list, but then I wouldn't know who was accepted before and didn't confirm in time and who was just newly brought out of the waiting list and has been accepted (as in I need to give this person more time before I accept someone else in their spot).

**Comment by juopmu** [comment]
Idea: Instead of adding another column, could we switch the radio button for those who haven't confirmed on time into a message stating, e.g. "Not confirmed on time"? I wonder whether the table is becoming too difficult to handle if we keep adding more columns.

**Comment by ferbsx** [comment]
A radio button is also a good idea :) 

(I'm not sure how that will then look in the downloadable csv file, but as long as the status can somehow be read in the file, It's good for me 👍 )
