### ISSUE TITLE
New column on application list: "canceled"

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#190]
Some attendees that were selected, cancel so I set them to "rejected" on the app. Now I have the problem, that I want to select attendees from the original "rejected" list but don't know which ones have already canceled and which had actually been rejected.

**Comment by juopmu** [comment]
Idea: Add a cancel link to the confirmation link in the selection (and possibly reminder) e-mail so if someone clicks the link, they will be set to "canceled" automatically. But also see my comment on the "confirmed too late" issue. Is there a way we can avoid adding too many columns and making the table hard to work with?

**Comment by ferbsx** [comment]
Awesome idea! I really like the canceling link!  <3

**Comment by simaofreitas** [comment]
Closed via https://github.com/rubymonsters/rgbapp/pull/199
