### ISSUE TITLE
Changes to the coaches application form to workshops

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#243]
Hello, Thank you again for the awesome work.

Here are some stuff I would like to have changes on the coaches application form:
- [x] On top of this page, it would be amazing, if you could display the workshop details. Eg: 
![Screen Shot 2020-02-10 at 10 23 33 PM](https://user-images.githubusercontent.com/11502220/74191490-01d63200-4c54-11ea-854c-b75c45052e48.png)
- [x] change `installation party` with `Installation Get-Together`.
- [x] Add `I am a first-time coach`. With the description `first-time coach = someone who has never coached at a code curious or Rails Girls Berlin beginner workshop`. Answer options are: `Yes` or `No` or `Other`. If they choose the latter they should be able to make a comment.
Similar to this:
![Screen Shot 2020-02-10 at 10 20 55 PM](https://user-images.githubusercontent.com/11502220/74191304-a73cd600-4c53-11ea-8b21-2fa1b26c63ee.png)
- [x] Add `I will attend the coach the coaches` with a small description saying `This is to help and familiarize you with the topics of the workshop, we suggest every coach to be present especially first-time coaches`. Answers could be `Yes`, `No` or `Maybe`
![Screen Shot 2020-02-10 at 10 21 37 PM](https://user-images.githubusercontent.com/11502220/74191345-bb80d300-4c53-11ea-971f-c87059fafc8e.png)
- [x] To the lightning talk question description `The talk should be understandable for beginners and not longer than 5 minutes.`, it would be awesome if you could add `We especially welcome more inspirational talks, from women/under-represented groups in tech. This could be about what got you into tech or what cool projects you've done or are interested in doing.`
- [x] Add `Is your company interested in sponsoring code curious?`, Answer is a box where they can write free text.

Thank you 🚀

**Comment by juopmu** [comment]
@ferbsx We completed all the issues. I omitted the options for "first-time coaching" and "coach the coaches". I think Yes is enough. If they want to add comments, they still have the comments box at the end. What do you think?
