### ISSUE TITLE
Missing Contribution Guideline

### ISSUE THREAD

**Issue by MariaAngella** [rubymonsters/rgbapp#259]
As guest contributors, we were looking for guidelines that we can employ to allow us  better our contribution into the codebase effectively. More like the rules that govern collaborations.

And if possible, Could this be addressed inside the ReadMe file so that it is easily seen?

Thank you and Regards,
#Team Chosen

**Comment by juopmu** [comment]
@MariaAngella Please let us know if you need any extra information in the contributing guidelines. We're happy to add infos.

**Comment by joycesand** [comment]
Thank you @juopmu, we are going to look into the readMe file and get back to you soon.
regards 
Team Chosen

**Comment by MariaAngella** [comment]
@juopmu, thank you for addressing this issue, 
the guidelines are now simple and precise.

We've also managed to clone and run the app successfully.

Warm Regards,
Team Chosen
