### ISSUE TITLE
Missing Issue templates

### ISSUE THREAD

**Issue by MariaAngella** [rubymonsters/rgbapp#260]
If we wanted to write a bug report, where would we find the guidelines and proper formats for writing one?

Because During code refactoring, continuous Integration and Development, there's need for effective communication between stakeholders, development and testing teams. 
Unclear requirements and misinterpretation of requirements are two major factors causing defects in software.

**Comment by juopmu** [comment]
@MariaAngella Thank you for pointing this out to us. I have added the standard templates for now. Please let us know if they work for you.

**Comment by joycesand** [comment]
Thank you @juopmu , we will look into that and get back to you soon.
