### ISSUE TITLE
Release next workshop \o/

### ISSUE THREAD

**Issue by porras** [rubymonsters/rgbapp#39]
These things should be done in order for people to start signing up:

- [x] Merge #13 
  - [x] Write actual email text
  - [x] Configure email service
  - [x] Configure `From:` email
- [x] Setup subdomain (e.g. `rgbapp.herokuapp.com`)
- [x] Clean test data (events and applications)
- [x] Add workshop data
- [x] Create accounts for organizers

Things that would be nice but aren't a prerequisite:

- <s>#35</s>
- #32

**Comment by juopmu** [comment]
To change the subdomain name, we have to contact Katja to transfer name management rights.

**Comment by juopmu** [comment]
Name for subdomain: rgbworkshopapplication.herokuapp.com
