### ISSUE TITLE
Basic design and layout

### ISSUE THREAD

**Issue by porras** [rubymonsters/rgbapp#4]
Form looks like this:

![screen shot 2017-03-06 at 20 14 22](https://cloud.githubusercontent.com/assets/3830/23625482/9b9574d4-02a9-11e7-900c-f089af97749d.png)

Should be more red and nice like [the rest of the website](http://railsgirlsberlin.de/)

**Comment by ferbsx** [comment]
Logo: 
![rgb_logo](https://cloud.githubusercontent.com/assets/11502220/23896756/cf59b2ba-08aa-11e7-85ac-86e310b44b48.jpg)

Colors:
(rgb-hexcolors)
RGB-Red: #c4220d

Heart: 
green: #6BB648
blue: #6B9DD4
yellow: #E8E561
piink: #DC72AB

Font Web: Open Sans
