### ISSUE TITLE
Customize email with templates from admin view

### ISSUE THREAD

**Issue by CarolinaGri** [rubymonsters/rgbapp#57]
Confirmation emails should be editable and customisable to the upcoming event.

**Comment by juopmu** [comment]
We could try to implement this using the gems mustache or liquid. Takes some work.

**Comment by juopmu** [comment]
Things to add:

- [ ] Customizable e-mails:
  - [ ] Application
  - [ ] Selection
  - [ ] Rejection (later: waiting list)
  - [ ] Reminder
- [ ] Separate form for templates
  - [ ] Add help for templates (basics of mustache + list of available variables)
- [ ] Default template or way to copy templates from previous events
- [ ] Add validation for errors in template (e.g. wrong variable) OR preview
