### ISSUE TITLE
German translations of the form

### ISSUE THREAD

**Issue by porras** [rubymonsters/rgbapp#6]

**Comment by Powerglove** [comment]
The app will be in english and german only (not more languages), so I don't know if it makes sense to use a gem like http://guides.rubyonrails.org/i18n.html or just have both languages "next to each other", like on the current RGB website. I guess buttons are also understandable in english only? @porras @nerdbabe @ferbsx

**Comment by ferbsx** [comment]
I agree with Johanna on this. We are this time also planning on doing the starting presentation only in English, so it is kind of a requirement to understand an ok level of English.
