### ISSUE TITLE
Number the applications

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#93]
Hi, this is really knit-picking and not a pressing issue, but I would love to have a column numbering the applications coming in. 

So like on the left to the select column, I would love to have a numbering column. I know there's a total number on top but it would make it way easier to talk about applicants if there are numbers at the side :)

![screen shot 2018-07-02 at 2 55 36 pm](https://user-images.githubusercontent.com/11502220/42165313-0c3de614-7e08-11e8-82ef-580d18819b0c.png)

**Comment by agatakrawczyk** [comment]
We try to deploy this week.

**Comment by ferbsx** [comment]
@agatakrawczyk  @juopmu Just wondering, how are the numbers ordered?

![screen shot 2018-07-10 at 1 54 18 am](https://user-images.githubusercontent.com/11502220/42481758-546239d6-83e4-11e8-9a7b-62579a392ecc.png)
